/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/myURImodel3.glb --output MyURImodel3.jsx 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/myURImodel3.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={54351.413} decay={2} position={[4.076, 5.904, -1.005]} rotation={[-1.839, 0.602, 1.932]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.895} position={[7.359, 4.958, 6.926]} rotation={[-0.627, 0.71, 0.441]} />
      <mesh geometry={nodes.Bliss_Hall.geometry} material={materials['Material.002']} position={[214.439, 0, -314.992]} rotation={[Math.PI, -1.54, Math.PI]} scale={[20.504, 40.774, 47.901]} />
      <mesh geometry={nodes.East_Hall.geometry} material={materials['Material.002']} position={[251.444, 0, -162.974]} scale={[18.861, 37.507, 44.063]} />
      <mesh geometry={nodes.Lippitt_Hall.geometry} material={materials['Material.002']} position={[35.783, 0.792, -354.799]} rotation={[-Math.PI, 0.031, -Math.PI]} scale={[20.504, 40.774, 47.901]} />
      <mesh geometry={nodes._Edwards_Auditorium.geometry} material={materials['Material.002']} position={[215.578, 0, 196.52]} scale={[31.284, 32.33, 37.981]} />
      <mesh geometry={nodes.Davis_Hall.geometry} material={materials['Material.002']} position={[-199.375, 0, -236.084]} rotation={[Math.PI, -1.514, Math.PI]} scale={[18.843, 37.507, 30.51]} />
      <mesh geometry={nodes.Carlotti_Administration_Building.geometry} material={materials['Material.002']} position={[-172.943, 6, -119.083]} rotation={[0, -0.044, 0]} scale={[-14.977, -29.783, -34.989]} />
      <mesh geometry={nodes.Bellentine_Hall.geometry} material={materials['Material.002']} position={[-58.639, 0, -393.433]} scale={[18.861, 37.507, 44.063]} />
      <mesh geometry={nodes.Taft_Hall.geometry} material={materials['Material.002']} position={[-199.511, -0.422, -321.269]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[18.843, 37.507, 30.51]} />
      <mesh geometry={nodes.Kirk_Center_for_Advanced_Technology.geometry} material={materials['Material.002']} position={[297.576, 0, -466.88]} scale={[18.861, 37.507, 55.766]} />
      <mesh geometry={nodes.The_Fascitelli_Center_for_Advance_Engineering.geometry} material={materials['Material.002']} position={[192.513, 4.021, -581.203]} rotation={[Math.PI, -1.544, Math.PI]} scale={[13.294, 26.422, 72.008]} />
      <mesh geometry={nodes.Kirk_Applied_Engineering_Lab.geometry} material={materials['Material.002']} position={[386.248, 0.546, -542.76]} rotation={[0, -0.011, 0]} scale={[18.893, 37.507, 62.425]} />
      <mesh geometry={nodes.Swan_Hall.geometry} material={materials['Material.002']} position={[209.378, 0, 440.371]} scale={[43.814, 32.33, 41.69]} />
      <mesh geometry={nodes.Green_Hall.geometry} material={materials['Material.002']} position={[10.907, 0, 326.636]} scale={[13.495, 37.507, 51.949]} />
      <mesh geometry={nodes.Chemical_Engineering.geometry} material={materials['Material.002']} position={[16.056, 0, -558.227]} rotation={[0, Math.PI / 2, 0]} scale={[15.411, 30.646, 45.565]} />
      <mesh geometry={nodes.Quinn_Hall.geometry} material={materials['Material.002']} position={[-237.922, 0, 405.745]} rotation={[Math.PI, -0.003, 0]} scale={[-16.606, -47.555, -47.684]} />
      <mesh geometry={nodes.Fogarty_Hall.geometry} material={materials['Material.002']} position={[-235.513, 0, 583.391]} rotation={[0, -1.55, 0]} scale={[23.569, 37.507, 80.879]} />
      <mesh geometry={nodes['Robert_L_Carothers_Library_&_Learning_Commons'].geometry} material={materials['Material.002']} position={[-278.744, 0, -481.486]} rotation={[0, -0.062, -Math.PI]} scale={[-92.078, -37.507, -59.402]} />
      <mesh geometry={nodes.Chafee_Social_Science_Center.geometry} material={materials['Material.002']} position={[-250.674, 0.863, -938.954]} rotation={[-Math.PI, 0.055, 0]} scale={[-63.67, -25.935, -41.075]} />
      <mesh geometry={nodes.Woodward_Hall.geometry} material={materials['Material.002']} position={[-45.074, -1.355, -889.14]} rotation={[0, -0.04, 0]} scale={[14.009, 37.507, 94.419]} />
      <mesh geometry={nodes.CBLS.geometry} material={materials['Material.002']} position={[-39.378, 0.091, -1041.283]} rotation={[0, -0.04, -Math.PI]} scale={[-14.003, -37.507, -62.505]} />
      <mesh geometry={nodes.Fine_Arts_Center.geometry} material={materials['Material.002']} position={[674.285, -4.14, -722.748]} rotation={[-Math.PI, 0.249, -Math.PI]} scale={[18.893, 37.507, 62.425]} />
      <mesh geometry={nodes.Coastal_Institute.geometry} material={materials['Material.002']} position={[274.104, -2.947, -1288.992]} rotation={[-Math.PI, 0.175, -Math.PI]} scale={[13.193, 26.031, 85.981]} />
      <mesh geometry={nodes.Rodman_Hall.geometry} material={materials['Material.002']} position={[-319.578, 0, -657.489]} rotation={[0, -0.044, 0]} scale={[16.602, 47.555, 38.153]} />
      <mesh geometry={nodes['Center_for_Biotechnology_&_Life_Sciences'].geometry} material={materials['Material.002']} position={[-234.104, 3.207, -1351.334]} rotation={[0, -0.04, 0]} scale={[16.604, 44.473, 79.887]} />
      <mesh geometry={nodes.Washburn_Hall.geometry} material={materials['Material.002']} position={[239.406, 0, -4.589]} rotation={[0, -0.039, 0]} scale={[18.85, 37.507, 42.4]} />
      <group position={[-324.441, 0.3, -13.709]} rotation={[0, 0.01, 0]} scale={2.469}>
        <mesh geometry={nodes.map_7osm_paths_footway002.geometry} material={materials['paths_footway.002']} />
        <mesh geometry={nodes.map_7osm_paths_footway002_1.geometry} material={materials.paths_footway} />
      </group>
      <mesh geometry={nodes['Beaupre_Center_for_Chemical_&_Forensic_Sciences'].geometry} material={materials['Material.002']} position={[-390.66, -3.347, -1200.865]} rotation={[Math.PI, -1.478, Math.PI]} scale={[14.009, 37.507, 94.419]} />
      <mesh geometry={nodes.White_Hall.geometry} material={materials['Material.002']} position={[-567.83, -0.675, -1339.119]} rotation={[-Math.PI, 0.462, -Math.PI]} scale={[13.193, 26.031, 85.981]} />
      <mesh geometry={nodes.Social_Sciences_Research_Center.geometry} material={materials['Material.002']} position={[-248.085, 3.844, -1350.436]} rotation={[0, -0.04, 0]} scale={[16.604, 44.473, 79.887]} />
      <mesh geometry={nodes.Mulicultural_Center.geometry} material={materials['Material.002']} position={[-398.924, 2.169, -66.519]} rotation={[Math.PI, -1.514, Math.PI]} scale={[18.843, 37.507, 30.51]} />
      <mesh geometry={nodes.Memorial_Union.geometry} material={materials['Material.002']} position={[-414.493, 3.991, 250.576]} rotation={[-3.137, 0.003, -3.14]} scale={[43.814, 32.33, 41.69]} />
      <mesh geometry={nodes.Tyler_Hall.geometry} material={materials['Material.002']} position={[-20.04, -2.141, -991.499]} rotation={[0, -0.04, -Math.PI]} scale={[-14.003, -37.507, -62.505]} />
    </group>
  )
}

useGLTF.preload('/myURImodel3.glb')
