/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/myURImodel2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/myURImodel2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bliss.geometry} material={materials['Material.002']} position={[214.439, 0, -314.992]} rotation={[Math.PI, -1.54, Math.PI]} scale={[20.504, 40.774, 47.901]} />
      <mesh geometry={nodes.East001.geometry} material={materials['Material.002']} position={[251.444, 0, -162.974]} scale={[18.861, 37.507, 44.063]} />
      <mesh geometry={nodes.Lippitt.geometry} material={materials['Material.002']} position={[35.783, 0.792, -354.799]} rotation={[-Math.PI, 0.031, -Math.PI]} scale={[20.504, 40.774, 47.901]} />
      <mesh geometry={nodes.Edwards.geometry} material={materials['Material.002']} position={[215.578, 0, 196.52]} scale={[31.284, 32.33, 37.981]} />
      <mesh geometry={nodes.DavisLeft.geometry} material={materials['Material.002']} position={[-199.375, 0, -236.084]} rotation={[Math.PI, -1.514, Math.PI]} scale={[18.843, 37.507, 30.51]} />
      <mesh geometry={nodes.Davis_.geometry} material={materials['Material.002']} position={[-172.943, 6, -119.083]} rotation={[0, -0.044, 0]} scale={[-14.977, -29.783, -34.989]} />
      <mesh geometry={nodes.Bellentine.geometry} material={materials['Material.002']} position={[-58.639, 0, -393.433]} scale={[18.861, 37.507, 44.063]} />
      <mesh geometry={nodes.Taft.geometry} material={materials['Material.002']} position={[-199.511, -0.422, -321.269]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[18.843, 37.507, 30.51]} />
      <mesh geometry={nodes.Kirk.geometry} material={materials['Material.002']} position={[297.576, 0, -466.88]} scale={[18.861, 37.507, 55.766]} />
      <mesh geometry={nodes.Kelley.geometry} material={materials['Material.002']} position={[192.513, 4.021, -581.203]} rotation={[Math.PI, -1.544, Math.PI]} scale={[13.294, 26.422, 72.008]} />
      <mesh geometry={nodes.Gilbreth.geometry} material={materials['Material.002']} position={[386.248, 0.546, -542.76]} rotation={[0, -0.011, 0]} scale={[18.893, 37.507, 62.425]} />
      <mesh geometry={nodes.Independence.geometry} material={materials['Material.002']} position={[209.378, 0, 440.371]} scale={[43.814, 32.33, 41.69]} />
      <mesh geometry={nodes.Green.geometry} material={materials['Material.002']} position={[10.907, 0, 326.636]} scale={[13.495, 37.507, 51.949]} />
      <mesh geometry={nodes.Pharm.geometry} material={materials['Material.002']} position={[16.056, 0, -558.227]} rotation={[0, Math.PI / 2, 0]} scale={[15.411, 30.646, 45.565]} />
      <mesh geometry={nodes.Quinn001.geometry} material={materials['Material.002']} position={[-237.922, 0, 405.745]} rotation={[Math.PI, -0.003, 0]} scale={[-16.606, -47.555, -47.684]} />
      <mesh geometry={nodes.Fogarty.geometry} material={materials['Material.002']} position={[-235.513, 0, 583.391]} rotation={[0, -1.55, 0]} scale={[23.569, 37.507, 80.879]} />
      <mesh geometry={nodes.Library.geometry} material={materials['Material.002']} position={[-278.744, 0, -481.486]} rotation={[0, -0.062, -Math.PI]} scale={[-92.078, -37.507, -59.402]} />
      <mesh geometry={nodes.Chafee.geometry} material={materials['Material.002']} position={[-252.145, 0, -907.494]} rotation={[-Math.PI, 0.055, 0]} scale={[-63.67, -25.935, -41.075]} />
      <mesh geometry={nodes.Tyler.geometry} material={materials['Material.002']} position={[111.047, 0, -796.914]} rotation={[Math.PI, -1.544, Math.PI]} scale={[13.097, 26.031, 70.942]} />
      <mesh geometry={nodes.Woodward.geometry} material={materials['Material.002']} position={[-68.318, 0, -760.083]} rotation={[0, -0.04, 0]} scale={[14.009, 37.507, 94.419]} />
      <mesh geometry={nodes.CBLS.geometry} material={materials['Material.002']} position={[-39.378, 0.091, -1041.283]} rotation={[0, -0.04, -Math.PI]} scale={[-14.003, -37.507, -62.505]} />
      <mesh geometry={nodes.Gilbreth001.geometry} material={materials['Material.002']} position={[674.285, -4.14, -722.748]} rotation={[-Math.PI, 0.249, -Math.PI]} scale={[18.893, 37.507, 62.425]} />
      <mesh geometry={nodes.Tyler001.geometry} material={materials['Material.002']} position={[165.274, 0, -1019.43]} rotation={[-Math.PI, 0.175, -Math.PI]} scale={[13.193, 26.031, 85.981]} />
      <mesh geometry={nodes.Rodman.geometry} material={materials['Material.002']} position={[-319.578, 0, -657.489]} rotation={[0, -0.044, 0]} scale={[16.602, 47.555, 38.153]} />
      <mesh geometry={nodes.Research.geometry} material={materials['Material.002']} position={[-203.148, 0, -1099.621]} rotation={[0, -0.04, 0]} scale={[16.604, 44.473, 79.887]} />
      <mesh geometry={nodes.Gilbreth002.geometry} material={materials['Material.002']} position={[-340.856, 0.546, -1136.4]} rotation={[Math.PI, -1.542, Math.PI]} scale={[11.482, 37.507, 60.043]} />
      <mesh geometry={nodes.Washburn.geometry} material={materials['Material.002']} position={[239.406, 0, -4.589]} rotation={[0, -0.039, 0]} scale={[18.85, 37.507, 42.4]} />
      <group position={[-324.441, 0.3, -13.709]} rotation={[0, 0.01, 0]} scale={2.469}>
        <mesh geometry={nodes.map_7osm_paths_footway002.geometry} material={materials['paths_footway.002']} />
        <mesh geometry={nodes.map_7osm_paths_footway002_1.geometry} material={materials.paths_footway} />
      </group>
    </group>
  )
}

useGLTF.preload('/myURImodel2.glb')
