/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\myURImodel2.glb --transform
Files: public\myURImodel2.glb [62.57KB] > C:\Users\kkgam\OneDrive\Desktop\Living-Labs-Code\LivingLabsWeb\myURImodel2-transformed.glb [17.98KB] (71%)
*/

import React from 'react'
import { useGLTF, Html } from '@react-three/drei'

const LABEL_STYLE = {
  background: 'rgba(0,0,0,0.65)',
  color: '#fff',
  padding: '2px 7px',
  borderRadius: 4,
  fontSize: 11,
  fontFamily: 'monospace',
  whiteSpace: 'nowrap',
  border: '1px solid rgba(255,255,255,0.3)',
  pointerEvents: 'none',
}

function BuildingLabel({ name, yOffset = 55 }) {
  return (
    <Html position={[0, yOffset, 0]} center style={{ pointerEvents: 'none' }}>
      <div style={LABEL_STYLE}>{name}</div>
    </Html>
  )
}

export function Model(props) {
  const { nodes, materials } = useGLTF('/myURImodel2.glb')
  const bld = materials['Material.002']
  const path = materials['paths_footway.002']

  return (
    <group {...props} dispose={null} rotation={[0, Math.PI / 2, 0]}>

      <group position={[214.439, 0, -314.992]}>
        <mesh geometry={nodes['Bliss'].geometry} material={bld} quaternion={[0, -0.71783, 0, 0.69622]} scale={[20.504, 40.774, 47.901]} />
        <BuildingLabel name="Bliss" />
      </group>

      <group position={[251.444, 0, -162.974]}>
        <mesh geometry={nodes.East001.geometry} material={bld} quaternion={[0, 0, 0, 1]} scale={[18.861, 37.507, 44.063]} />
        <BuildingLabel name="East" />
      </group>

      <group position={[35.783, 0.792, -354.799]}>
        <mesh geometry={nodes['Lippitt'].geometry} material={bld} quaternion={[0, 0.99988, 0, 0.01531]} scale={[20.504, 40.774, 47.901]} />
        <BuildingLabel name="Lippitt" />
      </group>

      <group position={[215.578, 0, 196.52]}>
        <mesh geometry={nodes['Edwards'].geometry} material={bld} quaternion={[0, 0, 0, 1]} scale={[31.284, 32.33, 37.981]} />
        <BuildingLabel name="Edwards" />
      </group>

      <group position={[-199.375, 0, -236.084]}>
        <mesh geometry={nodes['DavisLeft'].geometry} material={bld} quaternion={[0, -0.72673, 0, 0.68692]} scale={[18.843, 37.507, 30.51]} />
        <BuildingLabel name="DavisLeft" />
      </group>

      <group position={[-172.943, 6, -119.083]}>
        <mesh geometry={nodes.Davis_.geometry} material={bld} quaternion={[0, -0.02184, 0, 0.99976]} scale={[-14.977, -29.783, -34.989]} />
        <BuildingLabel name="Davis" />
      </group>

      <group position={[-58.639, 0, -393.433]}>
        <mesh geometry={nodes['Bellentine'].geometry} material={bld} quaternion={[0, 0, 0, 1]} scale={[18.861, 37.507, 44.063]} />
        <BuildingLabel name="Bellentine" />
      </group>

      <group position={[-199.511, -0.422, -321.269]}>
        <mesh geometry={nodes['Taft'].geometry} material={bld} quaternion={[0, 0.99960, 0, 0.02815]} scale={[18.843, 37.507, 30.51]} />
        <BuildingLabel name="Taft" />
      </group>

      <group position={[297.576, 0, -466.88]}>
        <mesh geometry={nodes['Kirk'].geometry} material={bld} quaternion={[0, 0, 0, 1]} scale={[18.861, 37.507, 55.766]} />
        <BuildingLabel name="Kirk" />
      </group>

      <group position={[192.513, 4.021, -581.203]}>
        <mesh geometry={nodes['Kelley'].geometry} material={bld} quaternion={[0, -0.71665, 0, 0.69743]} scale={[13.294, 26.422, 72.008]} />
        <BuildingLabel name="Kelley" />
      </group>

      <group position={[386.248, 0.546, -542.76]}>
        <mesh geometry={nodes['Gilbreth'].geometry} material={bld} quaternion={[0, -0.00559, 0, 0.99998]} scale={[18.893, 37.507, 62.425]} />
        <BuildingLabel name="Gilbreth" />
      </group>

      <group position={[209.378, 0, 440.371]}>
        <mesh geometry={nodes['Independence'].geometry} material={bld} quaternion={[0, 0, 0, 1]} scale={[43.814, 32.33, 41.69]} />
        <BuildingLabel name="Independence" />
      </group>

      <group position={[10.907, 0, 326.636]}>
        <mesh geometry={nodes['Green'].geometry} material={bld} quaternion={[0, 0, 0, 1]} scale={[13.495, 37.507, 51.949]} />
        <BuildingLabel name="Green" />
      </group>

      <group position={[16.056, 0, -558.227]}>
        <mesh geometry={nodes['Pharm'].geometry} material={bld} quaternion={[0, 0.70711, 0, 0.70711]} scale={[15.411, 30.646, 45.565]} />
        <BuildingLabel name="Pharm" />
      </group>

      <group position={[-237.922, 0, 405.745]}>
        <mesh geometry={nodes.Quinn001.geometry} material={bld} quaternion={[0.99999, 0, -0.00126, 0]} scale={[-16.606, -47.555, -47.684]} />
        <BuildingLabel name="Quinn" yOffset={58} />
      </group>

      <group position={[-235.513, 0, 583.391]}>
        <mesh geometry={nodes['Fogarty'].geometry} material={bld} quaternion={[0, -0.69979, 0, 0.71435]} scale={[23.569, 37.507, 80.879]} />
        <BuildingLabel name="Fogarty" />
      </group>

      <group position={[-278.744, 0, -481.486]}>
        <mesh geometry={nodes['Library'].geometry} material={bld} quaternion={[0.03091, 0, -0.99952, 0]} scale={[-92.078, -37.507, -59.402]} />
        <BuildingLabel name="Library" yOffset={48} />
      </group>

      <group position={[-252.145, 0, -907.494]}>
        <mesh geometry={nodes['Chafee'].geometry} material={bld} quaternion={[0.99962, 0, 0.02752, 0]} scale={[-63.67, -25.935, -41.075]} />
        <BuildingLabel name="Chafee" yOffset={36} />
      </group>

      <group position={[111.047, 0, -796.914]}>
        <mesh geometry={nodes['Tyler'].geometry} material={bld} quaternion={[0, -0.71665, 0, 0.69743]} scale={[13.097, 26.031, 70.942]} />
        <BuildingLabel name="Tyler" yOffset={36} />
      </group>

      <group position={[-68.318, 0, -760.083]}>
        <mesh geometry={nodes['Woodward'].geometry} material={bld} quaternion={[0, -0.01990, 0, 0.99980]} scale={[14.009, 37.507, 94.419]} />
        <BuildingLabel name="Woodward" />
      </group>

      <group position={[-39.378, 0.091, -1041.283]}>
        <mesh geometry={nodes['CBLS'].geometry} material={bld} quaternion={[0.01990, 0, -0.99980, 0]} scale={[-14.003, -37.507, -62.505]} />
        <BuildingLabel name="CBLS" />
      </group>

      <group position={[674.285, -4.14, -722.748]}>
        <mesh geometry={nodes.Gilbreth001.geometry} material={bld} quaternion={[0, 0.99227, 0, 0.12413]} scale={[18.893, 37.507, 62.425]} />
        <BuildingLabel name="Gilbreth.001" />
      </group>

      <group position={[165.274, 0, -1019.43]}>
        <mesh geometry={nodes.Tyler001.geometry} material={bld} quaternion={[0, 0.99616, 0, 0.08756]} scale={[13.193, 26.031, 85.981]} />
        <BuildingLabel name="Tyler.001" yOffset={36} />
      </group>

      <group position={[-319.578, 0, -657.489]}>
        <mesh geometry={nodes['Rodman'].geometry} material={bld} quaternion={[0, -0.02184, 0, 0.99976]} scale={[16.602, 47.555, 38.153]} />
        <BuildingLabel name="Rodman" yOffset={58} />
      </group>

      <group position={[-203.148, 0, -1099.621]}>
        <mesh geometry={nodes['Research'].geometry} material={bld} quaternion={[0, -0.01990, 0, 0.99980]} scale={[16.604, 44.473, 79.887]} />
        <BuildingLabel name="Research" yOffset={55} />
      </group>

      <group position={[-340.856, 0.546, -1136.4]}>
        <mesh geometry={nodes.Gilbreth002.geometry} material={bld} quaternion={[0, -0.71720, 0, 0.69686]} scale={[11.482, 37.507, 60.043]} />
        <BuildingLabel name="Gilbreth.002" />
      </group>

      <group position={[239.406, 0, -4.589]}>
        <mesh geometry={nodes['Washburn'].geometry} material={bld} quaternion={[0, -0.01941, 0, 0.99981]} scale={[18.85, 37.507, 42.4]} />
        <BuildingLabel name="Washburn" />
      </group>

      <group position={[-324.441, 0.3, -13.709]}>
        <mesh geometry={nodes.map_7osm_paths_footway002.geometry} material={path} quaternion={[0, 0.00517, 0, 0.99999]} scale={[2.469, 2.469, 2.469]} />
      </group>

    </group>
  )
}

useGLTF.preload('/myURImodel2.glb')
