/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\myURImodel2.glb --transform 
Files: public\myURImodel2.glb [62.57KB] > C:\Users\kkgam\OneDrive\Desktop\Living-Labs-Code\LivingLabsWeb\myURImodel2-transformed.glb [17.98KB] (71%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/myURImodel2-transformed.glb')
  // rotate the entire model +90 degrees around Y so it matches scene orientation
  return (
    <group {...props} dispose={null} rotation={[0, Math.PI / 2, 0]}>
      <mesh geometry={nodes.Bliss.geometry} material={materials['Material.002']} position={[214.439, 0, -314.992]} rotation={[Math.PI, -1.54, Math.PI]} scale={[20.504, 40.774, 47.901]} />
      <mesh geometry={nodes.map_7osm_paths_footway001.geometry} material={materials['paths_footway.002']} position={[-324.441, 0.3, -13.709]} rotation={[0, 0.01, 0]} scale={2.469} />
    </group>
  )
}

useGLTF.preload('/myURImodel2-transformed.glb')
