import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Quantico } from 'next/font/google';
import { Onest } from 'next/font/google';
import { AuthProvider } from '@/lib/auth-context';

const quantico = Quantico({
  subsets: ['latin'],
  weight: ['400', '700'],
});
const onest = Onest({
  subsets: ['latin'],
  weight: ['400', '700'],
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
    <html lang="en">
      {/* suppressHydrationWarning prevents noisy dev-time hydration warnings caused
          by browser extensions or other client-only attribute changes (e.g. Grammarly)
          that mutate the DOM before React hydrates. Apply to a smaller element if you
          need more granular control. */}
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
